variables:
  SONAR_TOKEN: $SONAR_API_TOKEN # SonarQube project token
  SONAR_HOST_URL: $SONAR_URL # Base URL of SonarQube server
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
  GIT_DEPTH: 0 # Tells git to fetch all the branches of the project, required by the sonar analysis task
  DAST_WEBSITE: $DAST_URL # Website to be scanned in the DAST stage
  BUILD_PATH: target/demo-0.0.1-SNAPSHOT.jar
  KUBERNETES_CPU_REQUEST: 2
  KUBERNETES_CPU_LIMIT: 6
  KUBERNETES_MEMORY_REQUEST: 8Gi
  KUBERNETES_MEMORY_LIMIT: 16Gi

# Setup a cache for SonarQube
cache:
  key: ${CI_JOB_NAME}
  paths:
    - .sonar/cache

# Define the pipeline stages to be run
stages:
  - build
  - sast
  - deploy
  - dast

# Build the jar to be used
build:
  stage: build
  image:
    name: openjdk:11-jdk
  script: ./mvnw clean package
  artifacts:
    paths:
      - $BUILD_PATH

# Run code quality checks on the SonarQube server
sonarqube-check:
  stage: sast
  image:
    name: sonarsource/sonar-scanner-cli:latest
  allow_failure: true
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.java.binaries=$BUILD_PATH
  only:
    - merge_requests
    - master

# Deploy the app to the staging environment
staging-deploy:
  stage: deploy
  image:
    name: openjdk:11-jdk
  script:
    - curl --location "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=7.0.2&source=github-rel" | tar zx
    - ./cf api $CF_API
    - ./cf auth $CF_USER $CF_PASSWORD
    - ./cf target -o $CF_ORG -s $CF_SPACE
    - ./cf push -f manifest.yml
  only:
  - master

# Check for OWASP Top 10 web app vulnerabilities and output an HTML report
owasp-zap:
  stage: dast
  image:
    name: owasp/zap2docker-weekly
  allow_failure: true
  script:
    - mkdir /zap/wrk/
    - zap-baseline.py -r report.html -t $DAST_WEBSITE || true
    - cp /zap/wrk/report.html .
  artifacts:
    paths: ["report.html"]